### ISSUE TITLE
Epic: Ink Smart Contract (APAC Edition)

### ISSUE THREAD

**Issue by hieple7985** [hieple7985/polkaTicket#9]
- [ ] 01. Login With Wallets
- [ ] 02. Home, Action Menu, Events Listing
- [ ] 03. Search, Action Menu, Ticket Booking
- [ ] 04. Profile (Edit Profile & Listing)
- [ ] 05. Ticket Consumption
- [ ] 06. Event Management
- [ ] 07. Ticket Exchange
